/* Bilgi sayfalarinin metni (SSS, cerez, gizlilik, 404).

   Ana sayfanin sozlugu i18n.js'te; uzun metinler o dosyayi sisirmesin diye
   burada duruyor. Yeni dil eklerken buraya da bir anahtar gerekiyor; eksikse
   Turkcesi gosteriliyor. Cevaplarda sadece <b> etiketi kullaniliyor.      */

const PAGES = {
  tr: {
    home: "Ana sayfa",
    faq: {
      tag: "SSS", title: "Sık sorulanlar",
      lead: "Aracı kullanırken en çok takılınan yerler.",
      items: [
        ["Çıktılar nereye kaydediliyor?",
         "<b>Videolar → ClipClover</b> içinde, videonun adıyla açılan bir klasöre, part-01.mp4 diye. İş bitince <b>Klasörü aç</b> butonu seni doğrudan oraya götürür. Programı kaldırsan bile bu videolar silinmez."],
        ["Bir video ne kadar sürer?",
         "Üç adım var: indirme, caption açıksa transkript, sonra render. Render bu bilgisayarda videonun süresinin kabaca yedide biri kadar sürüyor. Transkript sadece caption açıkken çalışıyor ve genelde en uzun adım o oluyor."],
        ["Neden bazen çok yavaş?",
         "Yavaşlatan şey neredeyse her zaman transkript, o da sadece caption açıkken çalışıyor. <b>Caption'ı kapatırsan</b> iş birkaç kat hızlanır."],
        ["Önizleme gerçekten çıktının aynısı mı?",
         "Evet. Önizleme, render'ın kullandığı kadraj hesabından ve filtre zincirinden geçiyor; tek farkı videonun tamamı değil, tek bir kare olması."],
        ["Caption'lar neden kapalı geliyor?",
         "Caption yakmak transkript gerektirir, yani işi yavaşlatır. Başlık ve Part yazısı bu ayardan bağımsız, her zaman basılıyor."],
        ["İnternet gerekiyor mu?",
         "Sadece videoyu indirirken. Transkript ve render tamamen bu bilgisayarda çalışıyor; altyazı modeli ilk kullanımda bir kez iniyor, sonrasında çevrimdışı çalışıyor."],
        ["Ayarlarım ve geçmişim nerede duruyor?",
         "Tarayıcının kendi deposunda, bu bilgisayarda. <b>Yedek indir</b> ile JSON olarak alıp başka bir bilgisayarda <b>Yedekten yükle</b> ile geri koyabilirsin."],
        ["Temizle butonu neyi siler?",
         "Sadece indirilen kaynak videoları ve ara dosyaları. Render ettiğin partlara hiç dokunmaz."],
      ],
    },
    cookies: {
      tag: "Çerez politikası", title: "Çerezler",
      lead: "Kısa cevap: bu araç çerez kullanmıyor.",
      items: [
        ["Çerez var mı?",
         "Hayır. Site sana çerez yazmıyor, okumuyor. Onay kutusu da bu yüzden yok."],
        ["Peki ayarlarım nasıl hatırlanıyor?",
         "Tarayıcının kendi deposunda şunlar duruyor: dil, part süresi, video boyutu gibi ayarlar, iş geçmişi, beta anahtarını girdiğine dair bir işaret ve siteye verdiğin bağlanma izninin anahtarı. Aynı bilgilerin bir kopyası yardımcının klasöründeki bir dosyada da tutuluyor; sebebi şu: tarayıcı deposu adrese bağlı, yani siteden girdiğinle <b>localhost</b>'tan girdiğin ayrı ayrı hatırlanırdı. Hiçbiri internete gitmiyor."],
        ["Nasıl silerim?",
         "Tarayıcının site verilerini temizlemen yeterli. Geçmişini kaybetmek istemiyorsan önce <b>Yedek indir</b>."],
        ["Dışarıya giden bir şey var mı?",
         "Sayfanın yazı tipleri Google Fonts'tan çekiliyor; bu, tarayıcının Google'a yaptığı bir istektir ve orada standart sunucu kayıtları tutulabilir. Bunun dışında sayfa dışarıya bir şey göndermiyor — analitik, izleyici ve reklam yok."],
      ],
    },
    privacy: {
      tag: "Gizlilik", title: "Gizlilik",
      lead: "Araç tamamen senin bilgisayarında çalışıyor. Videon, sesin ve transkriptin hiçbir yere gönderilmiyor.",
      items: [
        ["Video nereye gidiyor?",
         "Hiçbir yere. İndirilen kaynak geçici klasöre, çıktılar çıktı klasörüne yazılıyor; ikisi de senin diskinde."],
        ["Transkript bulutta mı çıkarılıyor?",
         "Hayır. Altyazı modeli senin ekran kartında çalışıyor; ses dosyası bilgisayardan çıkmıyor."],
        ["Dışarıya yapılan istekler neler?",
         "Üç tane: videoyu indirmek için YouTube, ilk kullanımda altyazı modelini indirmek için model deposu, bir de sayfanın yazı tipleri için Google Fonts."],
        ["Sunucu dışarıya açık mı?",
         "Hayır. Sunucu yalnızca bu bilgisayarın kendi adreslerini dinliyor; aynı ağdaki başka bir cihaz bağlanamaz."],
        ["Kayıt tutuluyor mu?",
         "Sunucu penceresinde istek satırları görünüyor, o kadar. Hesap yok, analitik yok, kullanıcı takibi yok."],
        ["Beta anahtarı nereye gidiyor?",
         "Hiçbir yere. Anahtarın doğruluğu tarayıcının içinde kontrol ediliyor; sunucuya gönderilmiyor, kimin hangi anahtarı girdiği tutulmuyor. Kod açık, isteyen bakabilir."],
        ["Sorumluluk",
         "YouTube'dan video indirmek, kendi içeriğin veya izin aldığın içerik dışında YouTube kullanım şartlarına aykırıdır. Ne indireceğin sana ait bir karar."],
      ],
    },
    notfound: {
      tag: "404", title: "Sayfa bulunamadı",
      lead: "Aradığın sayfa yok. Yanlış bir bağlantıya tıklamış ya da adresi yazarken bir harf kaçırmış olabilirsin.",
      items: [],
    },
  },

  en: {
    home: "Home",
    faq: {
      tag: "FAQ", title: "Frequently asked",
      lead: "The things people get stuck on.",
      items: [
        ["Where do the parts get saved?",
         "Under <b>Videos → ClipClover</b>, in a folder named after the video, as part-01.mp4 and so on. When a job finishes, <b>Open folder</b> takes you straight there. Uninstalling the program never deletes them."],
        ["How long does a video take?",
         "Three steps: download, a transcript if captions are on, then render. Rendering takes roughly a seventh of the video's length on this machine. The transcript only runs with captions, and it is usually the longest step."],
        ["Why is it slow sometimes?",
         "It is almost always the transcript, and it only runs with captions. <b>Turn captions off</b> and the job is several times faster."],
        ["Is the preview really what I get?",
         "Yes. The preview goes through the same framing math and the same filter chain as the render; the only difference is that it is a single frame."],
        ["Why are captions off by default?",
         "Burning captions needs a transcript, which slows the job down. The title and the Part line are printed regardless of this setting."],
        ["Do I need internet?",
         "Only to download the video. Transcript and render run entirely on this machine; the subtitle model downloads once on first use and then works offline."],
        ["Where are my settings and history kept?",
         "In the browser's own storage, on this computer. <b>Export backup</b> saves them as JSON and <b>Import backup</b> restores them on another machine."],
        ["What does Clean up delete?",
         "Only downloaded source videos and intermediate files. It never touches the parts you rendered."],
      ],
    },
    cookies: {
      tag: "Cookie policy", title: "Cookies",
      lead: "Short answer: this tool uses no cookies.",
      items: [
        ["Are there cookies?",
         "No. The page neither writes nor reads cookies. That is why there is no consent banner."],
        ["Then how are my settings remembered?",
         "The browser's own storage holds: language, part length, video size and other settings, the job history, a marker that you entered a beta key, and the key for the permission you granted the site. A copy of the same information also sits in a file in the helper's folder, because browser storage is tied to the address — the site and <b>localhost</b> would remember you separately. None of it goes to the internet."],
        ["How do I delete it?",
         "Clearing site data in your browser is enough. Use <b>Export backup</b> first if you want to keep your history."],
        ["Does anything leave the machine?",
         "The page's fonts are fetched from Google Fonts, which is a request your browser makes to Google, and standard server logs may be kept there. Beyond that the page sends nothing out — no analytics, no trackers, no ads."],
      ],
    },
    privacy: {
      tag: "Privacy", title: "Privacy",
      lead: "The tool runs entirely on your computer. Your video, audio and transcript are never sent anywhere.",
      items: [
        ["Where does the video go?",
         "Nowhere. The download lands in a temporary folder and the parts in the output folder — both on your own disk."],
        ["Is the transcript made in the cloud?",
         "No. The subtitle model runs on your own graphics card; the audio file never leaves the machine."],
        ["Which outbound requests exist?",
         "Three: YouTube to fetch the video, the model repository once on first use, and Google Fonts for the page's typefaces."],
        ["Is the server reachable from outside?",
         "No. It listens only on this computer's own addresses; no other device on the network can connect."],
        ["Are there logs?",
         "Request lines show up in the server window, and that is all. No accounts, no analytics, no user tracking."],
        ["Where does the beta key go?",
         "Nowhere. The key is checked inside your browser; it is never sent to a server and no record is kept of who entered which key. The code is open, anyone can check."],
        ["Responsibility",
         "Downloading from YouTube is against its terms of service unless the content is yours or you have permission. What you download is your call."],
      ],
    },
    notfound: {
      tag: "404", title: "Page not found",
      lead: "There is nothing at this address. A link may be wrong, or a letter got lost while typing it.",
      items: [],
    },
  },

  de: {
    home: "Startseite",
    faq: {
      tag: "FAQ", title: "Häufige Fragen",
      lead: "Die Stellen, an denen es meistens hakt.",
      items: [
        ["Wo landen die Teile?",
         "Unter <b>Videos → ClipClover</b>, in einem Ordner mit dem Namen des Videos, als part-01.mp4 und so weiter. Nach dem Job führt <b>Ordner öffnen</b> direkt dorthin. Beim Deinstallieren bleiben sie erhalten."],
        ["Wie lange dauert ein Video?",
         "Drei Schritte: Herunterladen, bei eingeschalteten Untertiteln ein Transkript, dann Rendern. Das Rendern dauert auf diesem Rechner etwa ein Siebtel der Videolänge. Das Transkript läuft nur mit Untertiteln und ist meist der längste Schritt."],
        ["Warum ist es manchmal langsam?",
         "Fast immer wegen des Transkripts, und das läuft nur mit Untertiteln. <b>Schalte Untertitel aus</b>, dann ist der Job um ein Vielfaches schneller."],
        ["Ist die Vorschau wirklich das Ergebnis?",
         "Ja. Die Vorschau nutzt dieselbe Ausschnitt-Rechnung und dieselbe Filterkette wie das Rendern; nur eben als Einzelbild."],
        ["Warum sind Untertitel standardmäßig aus?",
         "Eingebrannte Untertitel brauchen ein Transkript und bremsen den Job. Titel und Part-Zeile werden unabhängig davon immer gesetzt."],
        ["Brauche ich Internet?",
         "Nur zum Herunterladen des Videos. Transkript und Rendern laufen komplett hier; das Untertitelmodell wird einmalig geladen und arbeitet danach offline."],
        ["Wo liegen Einstellungen und Verlauf?",
         "Im Speicher des Browsers, auf diesem Rechner. <b>Backup laden</b> sichert sie als JSON, <b>Backup einspielen</b> stellt sie woanders wieder her."],
        ["Was löscht Aufräumen?",
         "Nur heruntergeladene Quellvideos und Zwischendateien. Die gerenderten Teile bleiben unberührt."],
      ],
    },
    cookies: {
      tag: "Cookie-Richtlinie", title: "Cookies",
      lead: "Kurz: dieses Werkzeug verwendet keine Cookies.",
      items: [
        ["Gibt es Cookies?",
         "Nein. Die Seite schreibt und liest keine Cookies. Deshalb gibt es auch kein Einwilligungsbanner."],
        ["Wie werden Einstellungen dann gemerkt?",
         "Im Speicher des Browsers liegen: Sprache, Teil-Länge, Videogröße und weitere Einstellungen, der Verlauf, eine Markierung, dass du einen Beta-Schlüssel eingegeben hast, und der Schlüssel für die Berechtigung, die du der Seite gegeben hast. Dieselben Angaben liegen zusätzlich in einer Datei im Ordner des Helfers, weil der Browserspeicher an die Adresse gebunden ist — die Seite und <b>localhost</b> würden dich getrennt merken. Nichts davon geht ins Internet."],
        ["Wie lösche ich sie?",
         "Website-Daten im Browser löschen genügt. Vorher <b>Backup laden</b>, wenn der Verlauf erhalten bleiben soll."],
        ["Geht irgendetwas nach draußen?",
         "Die Schriften kommen von Google Fonts — eine Anfrage deines Browsers an Google, wo übliche Serverprotokolle anfallen können. Sonst sendet die Seite nichts: keine Analyse, kein Tracking, keine Werbung."],
      ],
    },
    privacy: {
      tag: "Datenschutz", title: "Datenschutz",
      lead: "Das Werkzeug läuft vollständig auf deinem Rechner. Video, Ton und Transkript werden nirgendwohin gesendet.",
      items: [
        ["Wohin geht das Video?",
         "Nirgendwohin. Der Download landet in einem temporären Ordner, die Teile im Ausgabeordner — beides auf deiner Festplatte."],
        ["Entsteht das Transkript in der Cloud?",
         "Nein. Das Modell läuft auf deiner Grafikkarte; die Audiodatei verlässt den Rechner nicht."],
        ["Welche Anfragen gehen nach außen?",
         "Drei: YouTube für das Video, einmalig das Modell-Repository und Google Fonts für die Schriften der Seite."],
        ["Ist der Server von außen erreichbar?",
         "Nein. Er lauscht nur auf den eigenen Adressen dieses Rechners; kein anderes Gerät im Netz kommt heran."],
        ["Werden Protokolle geführt?",
         "Im Serverfenster erscheinen Anfragezeilen, mehr nicht. Keine Konten, keine Analyse, kein Tracking."],
        ["Wohin geht der Beta-Schlüssel?",
         "Nirgendwohin. Der Schlüssel wird im Browser geprüft, nicht an einen Server geschickt; es wird nicht festgehalten, wer welchen Schlüssel eingegeben hat. Der Code ist offen, jeder kann nachsehen."],
        ["Verantwortung",
         "Das Herunterladen von YouTube verstößt gegen deren Nutzungsbedingungen, außer es sind eigene oder freigegebene Inhalte. Was du lädst, ist deine Entscheidung."],
      ],
    },
    notfound: {
      tag: "404", title: "Seite nicht gefunden",
      lead: "Unter dieser Adresse liegt nichts. Vielleicht stimmt ein Link nicht oder beim Tippen ist ein Buchstabe verloren gegangen.",
      items: [],
    },
  },

  fr: {
    home: "Accueil",
    faq: {
      tag: "FAQ", title: "Questions fréquentes",
      lead: "Là où ça coince le plus souvent.",
      items: [
        ["Où sont enregistrées les parties ?",
         "Dans <b>Vidéos → ClipClover</b>, dans un dossier au nom de la vidéo, sous la forme part-01.mp4. Une fois le travail fini, <b>Ouvrir le dossier</b> t'y emmène directement. La désinstallation ne les supprime pas."],
        ["Combien de temps ça prend ?",
         "Trois étapes : téléchargement, transcription si les sous-titres sont activés, puis rendu. Le rendu prend environ un septième de la durée de la vidéo sur cette machine. La transcription ne tourne qu'avec les sous-titres et c'est en général l'étape la plus longue."],
        ["Pourquoi c'est parfois lent ?",
         "C'est presque toujours la transcription, et elle ne tourne qu'avec les sous-titres. <b>Désactive-les</b> et le travail est plusieurs fois plus rapide."],
        ["L'aperçu correspond-il vraiment au rendu ?",
         "Oui. L'aperçu passe par le même calcul de cadrage et la même chaîne de filtres que le rendu ; c'est simplement une seule image."],
        ["Pourquoi les sous-titres sont-ils désactivés par défaut ?",
         "Les incruster demande une transcription, donc du temps. Le titre et la mention Part sont écrits dans tous les cas."],
        ["Faut-il une connexion ?",
         "Seulement pour télécharger la vidéo. Transcription et rendu tournent entièrement ici ; le modèle de sous-titres se télécharge une fois puis fonctionne hors ligne."],
        ["Où sont mes réglages et mon historique ?",
         "Dans le stockage du navigateur, sur cet ordinateur. <b>Exporter</b> les enregistre en JSON et <b>Importer</b> les restaure ailleurs."],
        ["Que supprime le nettoyage ?",
         "Uniquement les vidéos sources téléchargées et les fichiers intermédiaires. Jamais les parties déjà rendues."],
      ],
    },
    cookies: {
      tag: "Politique de cookies", title: "Cookies",
      lead: "Réponse courte : cet outil n'utilise aucun cookie.",
      items: [
        ["Y a-t-il des cookies ?",
         "Non. La page n'écrit ni ne lit de cookie. C'est pourquoi il n'y a pas de bandeau de consentement."],
        ["Alors comment mes réglages sont-ils retenus ?",
         "Le stockage du navigateur contient : la langue, la durée des parties, la taille de la vidéo et les autres réglages, l'historique, une marque indiquant que tu as saisi une clé bêta, et la clé de l'autorisation que tu as donnée au site. Les mêmes informations sont aussi copiées dans un fichier du dossier de l'assistant, car le stockage du navigateur dépend de l'adresse — le site et <b>localhost</b> te mémoriseraient séparément. Rien ne part sur internet."],
        ["Comment les effacer ?",
         "Effacer les données du site dans le navigateur suffit. Fais d'abord <b>Exporter</b> si tu veux garder l'historique."],
        ["Quelque chose sort-il de la machine ?",
         "Les polices viennent de Google Fonts : c'est une requête de ton navigateur vers Google, où des journaux serveur habituels peuvent être conservés. À part ça, la page n'envoie rien — pas d'analyse, pas de traceur, pas de publicité."],
      ],
    },
    privacy: {
      tag: "Confidentialité", title: "Confidentialité",
      lead: "L'outil tourne entièrement sur ton ordinateur. Ta vidéo, ton audio et ta transcription ne partent nulle part.",
      items: [
        ["Où va la vidéo ?",
         "Nulle part. Le téléchargement atterrit dans un dossier temporaire et les parties dans le dossier de sortie — tout sur ton disque."],
        ["La transcription se fait-elle dans le cloud ?",
         "Non. Le modèle tourne sur ta carte graphique ; le fichier audio ne quitte pas la machine."],
        ["Quelles requêtes sortent ?",
         "Trois : YouTube pour la vidéo, le dépôt du modèle une seule fois, et Google Fonts pour les polices de la page."],
        ["Le serveur est-il accessible de l'extérieur ?",
         "Non. Il n'écoute que les adresses locales de cet ordinateur ; aucun autre appareil du réseau ne peut s'y connecter."],
        ["Y a-t-il des journaux ?",
         "Des lignes de requêtes apparaissent dans la fenêtre du serveur, rien de plus. Pas de compte, pas d'analyse, pas de suivi."],
        ["Où va la clé bêta ?",
         "Nulle part. La clé est vérifiée dans ton navigateur ; elle n'est pas envoyée à un serveur et personne ne note qui a saisi quelle clé. Le code est ouvert, chacun peut vérifier."],
        ["Responsabilité",
         "Télécharger depuis YouTube va à l'encontre de ses conditions d'utilisation, sauf pour ton propre contenu ou avec autorisation. Ce que tu télécharges relève de toi."],
      ],
    },
    notfound: {
      tag: "404", title: "Page introuvable",
      lead: "Il n'y a rien à cette adresse. Un lien est peut-être erroné, ou une lettre s'est perdue en tapant.",
      items: [],
    },
  },
};
